#pragma once
#define VIAL_KEYBOARD_UID {0x7E, 0x64, 0xD9, 0x5A, 0xE1, 0x5E, 0x47, 0x40}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_OLED_ENABLE
#define OLED_DISPLAY_128X64
#define OLED_UPDATE_INTERVAL 50
#define OLED_TIMEOUT 60000