#pragma once

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_OLED_ENABLE

#define OLED_DISPLAY_128X64
#define OLED_UPDATE_INTERVAL 50
#define OLED_TIMEOUT 60000